In [2]:
# Code use to import the numpy library
import numpy as np

#### Numpy Library
NumPy is a powerful Python library used for numerical computations. It is particularly useful for creating and manipulating 1D to multidimensional arrays and performing a wide range of mathematical operations on them with ease. By leveraging efficient array operations, NumPy significantly reduces computation times, making it highly beneficial in fields like Machine Learning, where it plays a critical role in training models

#### Array
An array is a data structure that houses similar elements, meaning all elements are of the same data type.

- **1-D Arrays:** A 1-D array is a linear array that spans across a single dimension. It is a series of elements indexed from 0 to n-1, where n is the total number of elements.
- **2-D Arrays:** A 2-D array spans across two dimensions, often referred to as rows and columns (or x and y). It is also called a matrix and is indexed from (0,0) (row, column) to (n-1, m-1), where n and m represent the total number of rows and columns, respectively.
- **Multidimensional Arrays:** Multidimensional arrays extend beyond two dimensions (e.g., 3-D, 4-D, etc.). The indexing follows a similar pattern as in 1-D and 2-D arrays, with additional indices for each extra dimension.

In [3]:
# Creating a 1-D Array in Numpy


# var_nam = np.array([list of values],dtype) #if dtype left empty will automatically be detected
arr1 = np.array([11,22,33,44,55],int)
print("The array of integers is:\n",arr1)

arr2 = np.array(['a','b','c','d'])
print("The array of charaters is:\n",arr2)

arr3 = np.array(['JAVA','PYTHON','C++'],dtype=str)
print("The array of string is:\n",arr3)

# Using the view() function
arr4 = arr3.view()
print("Array created using View Function:\n" ,arr4)

# Using the copy() funtion
arr5 = arr2.copy()
print("Array Created using Copy Function\n", arr5)

# Main Difference between view() and copy(): The main difference between `view()` and `copy()` is that `view()` creates an array with the same data 
# as the original, meaning they share the same memory address, similar to reference variables in C++ (aka alias). As a result, changes made to the new array 
# created by `view()` will affect the original one. On the other hand, `copy()` creates a duplicate of the array with its own separate memory. 
# Therefore, changes made to the copied array do not affect the original array.

 

The array of integers is:
 [11 22 33 44 55]
The array of charaters is:
 ['a' 'b' 'c' 'd']
The array of string is:
 ['JAVA' 'PYTHON' 'C++']
Array created using View Function:
 ['JAVA' 'PYTHON' 'C++']
Array Created using Copy Function
 ['a' 'b' 'c' 'd']


In [39]:
# arrange() function creates an array via arranging elemets from first to last value give
# var_name = np.arange(first,last,dtype) #if only 1 number is given the first is considered as 0m adn dtype equal to numbers dtype.
arr6 = np.arange(14)
print("The Array of ints using the Arange Function:\n",arr6)

arr7 = np.arange(14,19,dtype = float)
print("The Array of flaots using the Arange Function:\n",arr7)

# linspace() function creates an array from start to end with a given number of elements, and it decided the interval of the spacing between those number
# with the help total number of given numbers and total numbers. (it generates equally space int/float array).
# var_name = np.linespace(first,last,total_numbers)
arr8 = np.linspace(12,24,5)
print("The Array created using linespace:\n",arr8)

# zeros() and ones() creates an array of specified number of 1s and 0s.
# var_name = np.zeros/ones((total_numbers))
arr9 = np.zeros((4))
print("The Array Created using zeros function:\n",arr9)

arr10 = np.ones((4))
print("The Array Created using ones function:\n",arr10)

# creating an array with uniform distributon between 0 to 1
arr13 = np.random.rand(3)  #(3,2) will generate a matrix
print("The Array created using random.rand():\n",arr13)

# creating an array with random number of normal distribution (centered around 0)
arr14 = np.random.randn(3)
print("The Array created using random.randn():\n",arr14)

# creating a array of random integers
arr15 = np.random.randint(1,50,8)  # form 1 to 50, 8 elements
print("The Array created using random.randint():\n",arr15)


The Array of ints using the Arange Function:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
The Array of flaots using the Arange Function:
 [14. 15. 16. 17. 18.]
The Array created using linespace:
 [12. 15. 18. 21. 24.]
The Array Created using zeros function:
 [0. 0. 0. 0.]
The Array Created using ones function:
 [1. 1. 1. 1.]
The Array created using random.rand():
 [0.98002823 0.46022503 0.47343337]
The Array created using random.randn():
 [-0.64220225 -1.09644119  0.44227705]
The Array created using random.randint():
 [ 9  2  5 28 20 28  7 16]


In [5]:
arr6 = np.arange(14)
print("The Array of ints using the Arange Function:\n",arr6)

# Accessing an element
print("ELement at 4th index or 5th place is:", arr6[4])

# Changing an element
arr6[4] = 90
arr6[0] = 1
print("new array after update:\n", arr6)

# Printing the size of the array, here .size is an attribute of the numpy array obj.
print("The size of the array is:", arr6.size)

# Finding the Dtype
print("The dtype of the array is:",arr6.dtype)

# np.<anything>(arr_var_name) is equivalent to arr_var_name.<anything>() in most cases.
# Mathematical And Statistical Functions
print("The mean of the array is:", arr6.mean())
print("The median of the array is:", np.median(arr6)) # you can't use arr6.median() as it is not a attribute of the obj nunmpy.array, instead it is a function.
print("The min value of the array:",arr6.min())
print("The max value of the array:", arr6.max())  # To know there index use argmax() or argmin()
print("The Sum of all the elements in the array:", arr6.sum())
print("The Product of all the values in the array:", arr6.prod())
print("Covariance:", np.cov(arr6))
print("Variance:", arr6.var())
print("Standard Deviation:", arr6.std())
print("The Sorted Array:", np.sort(arr6))
print("All elements raised to power of 4:", np.power(arr6,4))
print("Square root of all the values:", np.sqrt(arr6))
print("Absolute value of each element:", np.abs(arr6))
print("Sin value of each element:", np.sin(arr6))  #expects rinput in raidans
print("Cos value of each element:", np.cos(arr6))  
print("Tan value of each element:", np.tan(arr6))  
print("Log base 'e' of each element:",np.log(arr6))
print("Log base '10' of each element:",np.log10(arr6))
print("e to the power of each element (exponatial value):",np.exp(arr6))

The Array of ints using the Arange Function:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
ELement at 4th index or 5th place is: 4
new array after update:
 [ 1  1  2  3 90  5  6  7  8  9 10 11 12 13]
The size of the array is: 14
The dtype of the array is: int32
The mean of the array is: 12.714285714285714
The median of the array is: 7.5
The min value of the array: 1
The max value of the array: 90
The Sum of all the elements in the array: 178
The Product of all the values in the array: -1625952768
Covariance: 510.83516483516496
Variance: 474.3469387755103
Standard Deviation: 21.779507312506183
The Sorted Array: [ 1  1  2  3  5  6  7  8  9 10 11 12 13 90]
All elements raised to power of 4: [       1        1       16       81 65610000      625     1296     2401
     4096     6561    10000    14641    20736    28561]
Square root of all the values: [1.         1.         1.41421356 1.73205081 9.48683298 2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.4641016

In [6]:
# Operator that can be used on single arrays. operation is performed on each element.

arr11 = np.arange(25,34)
print("Original Array: ",arr11)
print("arr11 + 45: ", arr11+45)
print("arr11 - 10: ", arr11-10)
print("arr11 * 10: ", arr11*10)
print("arr11 / 10: ", arr11/10)
print("arr11 % 10: ", arr11%10)
print("arr11 // 10: ", arr11//10)

# Operator that can be used on multiple arrays. 
# operation is performed on each pair element of both array (pair made on the basis of index arr1[0] + arr2[0]).
# length of both the arrays should be the same

arr12 = np.array([11,12,13])
arr13 = np.array([14,15,16])
arr14 = np.array([17,18,19])

# Performing addition and subtraction
arr15 = arr12+arr13-arr14
print("New Array: ",arr15)

# Multiplication and division
arr16 = (arr12 * arr13)/arr14
print("New Array: ",arr16)

# Modulus or remainder
arr17 = arr12 % arr13
print("New Array: ",arr17)

# Integer division
arr18 = arr13 // arr12
print("New Array: ",arr18)

# Relational Operators
print("Are the element on arr12 >= arr13?: ",arr12 >= arr13)
print("Are the element on arr12 <= arr13?: ",arr12 <= arr13)
print("Are the element on arr12 == arr13?: ",arr12 == arr13)
print("Are the element on arr12 != arr13?: ",arr12 != arr13)


Original Array:  [25 26 27 28 29 30 31 32 33]
arr11 + 45:  [70 71 72 73 74 75 76 77 78]
arr11 - 10:  [15 16 17 18 19 20 21 22 23]
arr11 * 10:  [250 260 270 280 290 300 310 320 330]
arr11 / 10:  [2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3]
arr11 % 10:  [5 6 7 8 9 0 1 2 3]
arr11 // 10:  [2 2 2 2 2 3 3 3 3]
New Array:  [ 8  9 10]
New Array:  [ 9.05882353 10.         10.94736842]
New Array:  [11 12 13]
New Array:  [1 1 1]
Are the element on arr12 >= arr13?:  [False False False]
Are the element on arr12 <= arr13?:  [ True  True  True]
Are the element on arr12 == arr13?:  [False False False]
Are the element on arr12 != arr13?:  [ True  True  True]


In [7]:
# Creating multidimensional Array

d2arr1 = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",d2arr1)

d2arr2 = np.matrix('11 22; 33 44; 55 66')
print("2D Array:\n",d2arr2)

d2arr3 = np.reshape(arr11,(3,3))
print("2D Array:\n",d2arr3)

d2arr4 = np.zeros((3,4))
print("2D Array:\n",d2arr4)

d2arr5 = np.ones((3,4))
print("2D Array:\n",d2arr5)


2D Array:
 [[1 2 3]
 [4 5 6]]
2D Array:
 [[11 22]
 [33 44]
 [55 66]]
2D Array:
 [[25 26 27]
 [28 29 30]
 [31 32 33]]
2D Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2D Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
# Accessing Array elements

print(d2arr1[0][0])  #accessing the first element of first row
print(d2arr1[1][2]) # accessing the third element of second row

# Slicing
# [begin_row : end_row ; begin_col : end_col]
d2arr6 = np.reshape(range(100,500,20),(4,5))
print("Array: \n", d2arr6)

print("Printing all element:\n",d2arr6[:,:]) # if nothing given 0 and last index is considered
print("Printing Specific SLice:\n", d2arr6[1:,1:]) # begin row and column form index 1

# Similar type of slicing can be applied to a 1-D array
print("Original Array: ",arr11)
print("Sliced Array: ", arr11[1:5])  # [begin : end]

1
6
Array: 
 [[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
Printing all element:
 [[100 120 140 160 180]
 [200 220 240 260 280]
 [300 320 340 360 380]
 [400 420 440 460 480]]
Printing Specific SLice:
 [[220 240 260 280]
 [320 340 360 380]
 [420 440 460 480]]
Original Array:  [25 26 27 28 29 30 31 32 33]
Sliced Array:  [26 27 28 29]


In [35]:
# Some Matrix operations
d2arr7 = np.array([[10,60,40],[40,50,30],[50,60,40],[40,50,20]])
print("Original Array:\n", d2arr7)

# Taking the transpose (switching rows with columns)
print("Transpose Matrix:\n",d2arr7.transpose())

# Find Dimension of array
print("Dimension of Array:",d2arr7.ndim)

# Find the number of rows and columns
print("Row and Column: ",d2arr7.shape)

# Converting the Matrix to 1-D array
print("Array: ",d2arr7.flatten())

# Sorting on the basis of row and column
print("Sorting acc to Column:\n",np.sort(d2arr7,axis = 0)) # axis defins in what respect row(1) or columns(0) (aka row major or column major), 
                                                        # it will take the original array and put elements in that order.
print("Sorting acc to Row:\n",np.sort(d2arr7,axis = 1))

# Printing the Diagonal Elements
print("Diagonal Element:\n",d2arr7.diagonal()) 



# Some Mathematical Operations
d2arr8 = np.array([[10,20,30,40],[50,60,70,80]])
d2arr9 = np.array([11,22,33,44,55,66,77,88])
d2arr9 = np.reshape(d2arr9,(2,4))

print("Matrix 1:\n",d2arr8)
print("Matrix 2:\n",d2arr9)

print("Addition:\n",d2arr8+d2arr9)
print("Subtraction:\n",d2arr8-d2arr9)
print("Multiply:\n",d2arr8*d2arr9)   # Here each element of d2arr8 is multiplied to d2arr9 on the basis of its index. i.e d2arr8[0][0] * d2arr9[0][0]
print("Division:\n",d2arr8/d2arr9)   #Similar to above
print("Remainder:\n",d2arr8%d2arr9)
print("integer Division:\n",d2arr8//d2arr9)


# Matrix Mutiplication
d2arr10 = np.transpose(d2arr9)
print("Transposed Matrix:\n",d2arr10)
print("Matrix Multiplication:\n",d2arr8@d2arr10) # @ operator can be used or np.dot(var_name1,var_name_2)

# Similar to 1-D arrays, Relation operators exsist for multidimensional matrix.

Original Array:
 [[10 60 40]
 [40 50 30]
 [50 60 40]
 [40 50 20]]
Transpose Matrix:
 [[10 40 50 40]
 [60 50 60 50]
 [40 30 40 20]]
Dimension of Array: 2
Row and Column:  (4, 3)
Array:  [10 60 40 40 50 30 50 60 40 40 50 20]
Sorting acc to Column:
 [[10 50 20]
 [40 50 30]
 [40 60 40]
 [50 60 40]]
Sorting acc to Row:
 [[10 40 60]
 [30 40 50]
 [40 50 60]
 [20 40 50]]
Diagonal Element:
 [10 50 40]
Matrix 1:
 [[10 20 30 40]
 [50 60 70 80]]
Matrix 2:
 [[11 22 33 44]
 [55 66 77 88]]
Addition:
 [[ 21  42  63  84]
 [105 126 147 168]]
Subtraction:
 [[-1 -2 -3 -4]
 [-5 -6 -7 -8]]
Multiply:
 [[ 110  440  990 1760]
 [2750 3960 5390 7040]]
Division:
 [[0.90909091 0.90909091 0.90909091 0.90909091]
 [0.90909091 0.90909091 0.90909091 0.90909091]]
Remainder:
 [[10 20 30 40]
 [50 60 70 80]]
integer Division:
 [[0 0 0 0]
 [0 0 0 0]]
Transposed Matrix:
 [[11 55]
 [22 66]
 [33 77]
 [44 88]]
Matrix Multiplication:
 [[ 3300  7700]
 [ 7700 19140]]
